### ISSUE TITLE
Memory Leak - Modal presented Coordinator (iOS 13)

### ISSUE THREAD

**Issue by MSWagner** [allaboutapps/ios-starter#12]
A modal presented coordinator (**iOS 13 Devices**) creates **Memory Leaks** on **presentationControllerDidDismiss**.

The issue is reconstructable in the template code as example with the MoreCoordinator presented in the MainCoordinator:

```
private func showMoreModal() {
    let coordinator = MoreCoordinator()
        
    coordinator.onDone = { [unowned self] in
        self.dismissChildCoordinator(animated: true)
    }
        
    coordinator.start()
    
    present(coordinator, animated: true)
}
```

**_The MoreViewController is still in Memory after dismissing the MoreCoordinator._**

**Comment by mbuchetics** [comment]
Fixed (1c9c25a255e637c22a7575523d62260ad44db767, fa25218ba0733b130e28a2032f039472b3f2eb1f). It was caused by changing the `UIAdaptivePresentationControllerDelegate` during dismissal of the modally presented coordinator. For whatever reason, iOS 13 doesn't like that and causes the presented view controller to stay in memory (referenced by some internal variables). I removed `resetDelegate` alltogether as this wasn't needed anyway (I think 😬).
Check out `Coordinator.swift` for the complete implementation.
